/* ============================================================
   pdf.js — Professional A4 PDF generation for a client record
   ============================================================ */

function ltGenerateClientPDF(client, companyName, doc) {
  const { jsPDF } = window.jspdf;
  doc = doc || new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const marginX = 16;
  let y = 18;

  // Header
  doc.setFont("helvetica", "bold"); doc.setFontSize(15); doc.setTextColor(15, 61, 62);
  doc.text(companyName || "Loan Officer Toolkit", marginX, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(120);
  doc.text("Client Requirements & Loan Summary", marginX, y + 5.5);
  doc.setFontSize(9);
  doc.text("Date Generated: " + new Date().toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" }), pageW - marginX, y, { align: "right" });
  y += 12;
  doc.setDrawColor(214, 221, 218); doc.line(marginX, y, pageW - marginX, y); y += 8;

  // Applicant info
  doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(20);
  doc.text(client.applicantName || "Unnamed Applicant", marginX, y);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(90);
  doc.text(`Client ID: ${client.id}`, pageW - marginX, y, { align: "right" });
  y += 7;

  const progress = ltComputeProgress(client);
  const infoRows = [
    ["Contact Number", client.contact || "—"],
    ["Loan Amount", ltPeso(client.loanAmount)],
    ["Loan Term", client.loanTerm + " months"],
    ["Loan Type", LT_LOAN_TYPE_META[client.loanType] || client.loanType],
    ["Business Type", client.businessType === "corporation" ? "Corporation" : "Sole Proprietorship"],
    ["Interest Rate", (client.interestRate || 0) + "% per month"],
    ["Service Fee", (client.serviceFee || 0) + "%"],
    ["Status", (LT_CLIENT_STATUS_META[client.status] || {}).label || client.status],
    ["Date Created", ltFormatDate(client.dateCreated)],
    ["Completion", progress.pct + "%"]
  ];

  doc.setFontSize(9.5);
  let colX = marginX, rowY = y, col = 0;
  infoRows.forEach(([k, v]) => {
    doc.setFont("helvetica", "bold"); doc.setTextColor(70);
    doc.text(k + ":", colX, rowY);
    doc.setFont("helvetica", "normal"); doc.setTextColor(20);
    doc.text(String(v), colX + 34, rowY);
    col++;
    if (col % 2 === 0) { rowY += 6.5; colX = marginX; }
    else { colX = marginX + 92; }
  });
  y = rowY + (col % 2 !== 0 ? 6.5 : 0) + 4;

  if (client.notes) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(9.5); doc.setTextColor(70);
    doc.text("Notes:", marginX, y); y += 5;
    doc.setFont("helvetica", "normal"); doc.setTextColor(20);
    const noteLines = doc.splitTextToSize(client.notes, pageW - marginX * 2);
    doc.text(noteLines, marginX, y);
    y += noteLines.length * 4.5 + 4;
  }

  doc.setDrawColor(214, 221, 218); doc.line(marginX, y, pageW - marginX, y); y += 8;

  // Checklist
  doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.setTextColor(15, 61, 62);
  doc.text("Requirements Checklist", marginX, y); y += 3;
  doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor(90);
  doc.text(`${progress.verified} of ${progress.total} verified (${progress.pct}%)`, pageW - marginX, y, { align: "right" });
  y += 6;

  const visible = ltVisibleItems(client);
  const bySection = {};
  visible.forEach(it => { (bySection[it.section] = bySection[it.section] || []).push(it); });

  CHECKLIST_SCHEMA.forEach(sec => {
    const items = bySection[sec.key];
    if (!items || items.length === 0) return;
    if (y > 270) { doc.addPage(); y = 18; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.setTextColor(15, 61, 62);
    doc.text(sec.label, marginX, y); y += 6;
    items.forEach(it => {
      if (y > 280) { doc.addPage(); y = 18; }
      const state = ltGetItemState(client, sec.key, it.key);
      const meta = LT_STATUS_META[state.status];
      const box = state.status === "verified" ? "[x]" : "[ ]";
      doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(30);
      doc.text(`${box} ${it.label}`, marginX + 3, y);
      doc.setFont("helvetica", "bold");
      const statusColor = state.status === "verified" ? [30, 122, 76] : state.status === "rejected" ? [167, 51, 42] : state.status === "received" ? [180, 97, 10] : [120, 120, 120];
      doc.setTextColor(...statusColor);
      doc.text(meta.label, pageW - marginX, y, { align: "right" });
      y += 5;
      if (state.notes) {
        doc.setFont("helvetica", "italic"); doc.setFontSize(8.3); doc.setTextColor(110);
        const nLines = doc.splitTextToSize("Note: " + state.notes, pageW - marginX * 2 - 6);
        doc.text(nLines, marginX + 6, y);
        y += nLines.length * 4 + 2;
      }
    });
    y += 3;
  });

  doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(150);
  doc.text("Generated by Loan Officer Toolkit — figures and status are for internal tracking purposes.", marginX, 290);

  return doc;
}

function ltDownloadClientPDF(client, companyName) {
  const doc = ltGenerateClientPDF(client, companyName);
  doc.save(`${client.id}_${(client.applicantName || "client").replace(/[^a-z0-9]+/gi, "_")}.pdf`);
}

function ltDownloadAllClientsPDF(clients, companyName) {
  if (clients.length === 0) return;
  let doc = null;
  clients.forEach((c, i) => {
    if (i > 0) { doc.addPage(); }
    doc = ltGenerateClientPDF(c, companyName, doc);
  });
  doc.save("all_clients.pdf");
}
